Refactor rose.shinc library to be imported by bin/rose

diff --git a/bin/rose b/bin/rose
--- a/bin/rose
+++ b/bin/rose
@@ -3,51 +3,16 @@
 #--------------------------------------------------------------------
 # Run in strict-mode
 #--------------------------------------------------------------------
-shopt -s extglob
-set -o errtrace
-set -o errexit
-set -o nounset
-set -o pipefail # fail if any command in a pipeline fails
+shopt -s extglob  # enable extended globs
+set -o errtrace   # fail if any statement returns non-zero
+set -o errexit    # fail if command fails
+set -o nounset    # fail if variable is not set, i.e. "unbound"
+set -o pipefail   # fail if any command in a pipeline fails
 
-ROSE_SH_BIN_HOME="$(cd "$(dirname "$0")" && pwd)"
-ROSE_SH_HOME="$(cd "${ROSE_SH_BIN_HOME}/.." && pwd)"
-ROSE_SH_SCRIPTS_DIR="${ROSE_SH_HOME}/lib"
+ROSE_SH_HOME="$(cd "$(dirname "$0")/.." && pwd)"
+ROSE_SH_BIN_HOME="${ROSE_SH_HOME}/bin"
+ROSE_SH_LIB_HOME="${ROSE_SH_HOME}/lib"
 
-#--------------------------------------------------------------------
-# Modules
-#--------------------------------------------------------------------
-source "${ROSE_SH_SCRIPTS_DIR}/import.shinc" || false
-
-import rose/compile
-import rose/help
-
-import__allow_unbound_variables util/bash-preexec
-import util/logging
-
-#--------------------------------------------------------------------
-function rose::cli() {
-#--------------------------------------------------------------------
-  while (( "$#" )); do
-      arg="$1"
-      shift
-
-      case "$arg" in
-        -h|--help) rose::help "$@";;
-        compile) rose::compile "$@";;
-        *)
-            rose::log::error "Unrecognized argument: $arg"
-            rose::help "$@"
-            ;;
-      esac
-  done
-}
-
-#--------------------------------------------------------------------
-function rose::main() {
-#--------------------------------------------------------------------
-  rose::log::trace "Beginning execution of Rose::main"
-
-  rose::cli "$@"
-}
+source "${ROSE_SH_LIB_HOME}/rose/rose.shinc"
 
 rose::main ${@:---help}
